security:
  oauth2:
    client:
      clientId: 438553696941180
      clientSecret: 25db0e222b9bce5ff6b7aedbbbca549a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
